// Scans /games and /apps and builds the catalog object used everywhere
// else. Exports buildCatalog() so other scripts (build-site.mjs,
// build-releases.mjs) can use the same data without re-parsing a file.
// When run directly, also writes public/assets/catalog.js — a plain
// classic script (window.NULL_CATALOG = {...}) that every generated
// page includes before app.js.

import { readdirSync, statSync, existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, extname, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
export const ROOT = join(__dirname, "..");

const IMAGE_EXTS = [".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg"];

function slugToTitle(slug) {
  return slug
    .split("-")
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function readLabels(folderPath) {
  const labelFile = join(folderPath, "Label.txt");
  if (!existsSync(labelFile)) return ["Uncategorized"];
  try {
    const raw = readFileSync(labelFile, "utf-8").trim();
    if (!raw) return ["Uncategorized"];
    const parts = raw
      .split(/[\n,]/)
      .map((s) => s.trim())
      .filter(Boolean);
    return parts.length ? parts : ["Uncategorized"];
  } catch {
    return ["Uncategorized"];
  }
}

function findThumbnail(folderPath, slug) {
  let files;
  try {
    files = readdirSync(folderPath);
  } catch {
    return null;
  }
  const bySlug = files.find((f) => IMAGE_EXTS.includes(extname(f).toLowerCase()) && f.startsWith(slug));
  if (bySlug) return bySlug;
  return files.find((f) => IMAGE_EXTS.includes(extname(f).toLowerCase())) || null;
}

function findHtml(folderPath, slug) {
  let files;
  try {
    files = readdirSync(folderPath);
  } catch {
    return null;
  }
  const bySlug = files.find((f) => f.toLowerCase() === `${slug}.html`);
  if (bySlug) return bySlug;
  return files.find((f) => extname(f).toLowerCase() === ".html") || null;
}

function scanDirectory(kind, dirName) {
  const dirPath = join(ROOT, dirName);
  if (!existsSync(dirPath)) return [];

  const entries = readdirSync(dirPath).filter((name) => {
    try {
      return statSync(join(dirPath, name)).isDirectory();
    } catch {
      return false;
    }
  });

  const results = [];
  for (const slug of entries) {
    const folderPath = join(dirPath, slug);
    const html = findHtml(folderPath, slug);
    if (!html) {
      console.warn(`[catalog] Skipping ${kind}/${slug}: no HTML file found.`);
      continue;
    }
    const thumbnail = findThumbnail(folderPath, slug);
    const labels = readLabels(folderPath);

    results.push({
      id: slug,
      kind,
      title: slugToTitle(slug),
      // Root-relative, no leading slash — every generated page combines
      // this with its own "prefix" (relative path back to root) to get
      // a working link/asset URL regardless of how deep the page is.
      route: `${dirName}/${slug}/`,
      htmlFile: html, // bare filename, used directly by the player page in the same folder
      htmlPath: `${dirName}/${slug}/${html}`,
      thumbnail: thumbnail ? `${dirName}/${slug}/${thumbnail}` : null,
      labels,
    });
  }

  // Raw folder-scan order is preserved deliberately — the frontend's
  // "Newest" sort relies on it (closer to the top of the folder listing
  // = newer). A-Z / Z-A / Popular are computed at runtime instead.
  return results;
}

export function buildCatalog() {
  return {
    games: scanDirectory("game", "games"),
    apps: scanDirectory("app", "apps"),
  };
}

export function writeCatalogJs(catalog) {
  const outDir = join(ROOT, "public", "assets");
  mkdirSync(outDir, { recursive: true });
  const js = `// Auto-generated by scripts/generate-catalog.mjs — do not edit by hand.\nwindow.NULL_CATALOG = ${JSON.stringify(catalog)};\n`;
  writeFileSync(join(outDir, "catalog.js"), js);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const catalog = buildCatalog();
  writeCatalogJs(catalog);
  console.log(`[catalog] Generated catalog.js: ${catalog.games.length} game(s), ${catalog.apps.length} app(s).`);
}
